name: Testing API

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check files
        run: ls -la
      - name: Install Poetry
        run: |
          python -m pip install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
          check-latest: true
          cache: "poetry"
      - name: Install dependencies
        run: $HOME/.local/bin/poetry install --with dev --no-interaction

  black:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run black check
        run: $HOME/.local/bin/poetry run black --check .

  flake8:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run flake8 check
        run: $HOME/.local/bin/poetry run flake8 --count .

  mypy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run mypy check
        run: $HOME/.local/bin/poetry run mypy .

  pytest:
    runs-on: ubuntu-latest
    needs: setup
    services:
      api-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: api
          POSTGRES_USER: api
          POSTGRES_DB: api
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
    steps:
      - name: Run pytest check
        run: $HOME/.local/bin/poetry run pytest -vv --cov="api" .
        env:
          API_HOST: "0.0.0.0"
          API_DB_HOST: localhost
